#!/bin/bash

readonly VARIANT=indel
readonly INDIR=./annotated/${VARIANT}
readonly OUTDIR=./filtered/${VARIANT}
mkdir -p ${OUTDIR}

if [ $# -eq 0 ] || [ -z "$1" ] || [ ! -f "$1" ]
then
    echo "$0 - Apply an ensemble model (provided) to indel VCFs"
    echo "Usage: $0 modelfile"
    exit 
fi

readonly MODEL=$1

for inputfile in ${INDIR}/*gz
do
    sample=$( basename $inputfile | cut -f 1 -d . )
    outputfile=${OUTDIR}/${sample}.consensus.${VARIANT}.vcf  # note: no .gz, will get bgzipped anyway
    if [ ! -f ${outputfile} ] || [ ${inputfile} -nt ${outputfile} ]
    then
        echo $sample
        qsub -cwd -e logs -o logs -N Model_${sample}_${VARIANT} \
            -l h_vmem=2g \
            ./scripts/apply_model.sh ${MODEL} $inputfile $outputfile
    fi
done
