#!/bin/bash

export PATH=/u/jdursi/.local/bin:${PATH}
module load python/2.7.2
module load gcc/4.8.1 openblas python-packages/2
module load tabix/0.2.6

readonly VARIANT=snv_mnv

readonly NEWDIR=/oicr/data/pancanxfer/consensus/initial_consensus/annotated/${VARIANT}
readonly NEWDIR2=/oicr/data/pancanxfer/consensus/initial_consensus/annotated/caller_vafs/${VARIANT}
readonly OLDDIR=/.mounts/labs/simpsonlab/users/jdursi/interim_consensus/results/${VARIANT}
readonly MERGEDIR=./compare-to-interim/${VARIANT}

mkdir -p ${MERGEDIR}

samples=$( ls vafs | xargs -n1 basename | grep -v \.tbi | cut -f 1 -d . | sort | uniq )

for sample in $samples
do
    oldfile=${OLDDIR}/${sample}.merged.somatic.${VARIANT}.vcf
    newfile=${NEWDIR}/${sample}.annotated.${VARIANT}.vcf.gz
    newfile2=${NEWDIR2}/${sample}.annotated.${VARIANT}.vcf.gz

    if [ ! -f $newfile ] || [ ! -f $newfile2 ]
    then
        echo "${sample}: new file not present: one of ${newfile} ${newfile2}"
        continue
    fi
    if [ ! -f $oldfile ]
    then
        echo "${sample}: old file not present"
        continue
    fi
    echo -n ${sample}
    newcalls2=$( zgrep -cv "^#" $newfile2 )
    newcalls=$( zgrep -cv "^#" $newfile )
    oldcalls=$( grep -cv "^#" $oldfile )
    if [ $newcalls -ne $oldcalls ] || [ $newcalls2 -ne $oldcalls ]
    then
        echo ": mismatch number of calls (new: ${newcalls} ${newcalls2} old: ${oldcalls} )"
    else
        echo ""
    fi
    if [ ${newcalls} -eq 0 ] || [ ${oldcalls} -eq 0 ] || [ ${newcalls2} -eq 0 ]
    then
        continue
    fi

    outfile=${MERGEDIR}/${sample}.comparison.${variant}.vcf
    mergevcf -l interim,new_mutect_vafs,new_caller_vafs \
        ${oldfile} ${newfile} ${newfile2} \
        --ncallers \
        -o ${outfile}
done
