#!/bin/bash

export PATH=/u/jdursi/.local/bin:${PATH}
module load python/2.7.2
module load gcc/4.8.1 openblas python-packages/2
module load tabix/0.2.6
module load parallel

readonly MERGEDIR=./qc/compare-to-interim/${VARIANT}
readonly NJOBS=6

mkdir -p ${MERGEDIR}

ls vafs \
    | xargs -n1 basename \
    | grep -v \.tbi \
    | cut -f 1 -d . \
    | sort \
    | uniq \
    | parallel -j ${NJOBS} ./qc/compare_one_snv_to_interim.sh
