#!/bin/bash

export PATH=/u/jdursi/.local/bin:${PATH}
module load python/2.7.2
module load gcc/4.8.1 openblas python-packages/2
module load tabix/0.2.6

readonly VARIANT=indel

readonly DEFNEWDIR=/oicr/data/pancanxfer/consensus/initial_consensus/filtered/${VARIANT}
readonly DEFMERGEDIR=./qc/compare-to-interim/${VARIANT}

readonly OLDDIR=/.mounts/labs/simpsonlab/users/jdursi/interim_consensus/results/${VARIANT}_normed
readonly NEWDIR=${NEWDIR:-${DEFNEWDIR}}
readonly MERGEDIR=${MERGEDIR:-${DEFMERGEDIR}}

mkdir -p ${MERGEDIR}

samples=$( ls vafs | xargs -n1 basename | grep -v \.tbi | cut -f 1 -d . | sort | uniq )

for sample in $samples
do
    oldfile=${OLDDIR}/${sample}.merged.somatic.indel_normed.vcf   #note! not VARIANT
    newfile=${NEWDIR}/${sample}.consensus.${VARIANT}.vcf.gz

    if [ ! -f $newfile ] 
    then
        echo "${sample}: new file not present"
        continue
    fi
    if [ ! -f $oldfile ]
    then
        echo "${sample}: old file not present"
        continue
    fi

    outfile=${MERGEDIR}/${sample}.comparison.vcf
    if [ ! -f ${outfile} ] || [ ${newfile} -nt ${outfile} ]
    then
        echo -n ${sample} 
        newcalls=$( zgrep -cv "^#" $newfile )
        oldcalls=$( grep -cv "^#" $oldfile )
        if [ $newcalls -ne $oldcalls ]
        then
            echo ": mismatch number of calls (new: ${newcalls}, old: ${oldcalls})"
        else
            echo ""
        fi
        if [ ${newcalls} -eq 0 ] || [ ${oldcalls} -eq 0 ]
        then
            continue
        fi

        mergevcf -l old,new \
            ${oldfile} <( zgrep -v "^##contig" ${newfile} ) \
            --ncallers \
            -o ${outfile}
    fi
done
