#!/bin/bash

export PATH=/u/jdursi/.local/bin:${PATH}
module load python/2.7.2
module load gcc/4.8.1 openblas python-packages/2
module load tabix/0.2.6

readonly VARIANT=${VARIANT}

readonly NEWDIR=/oicr/data/pancanxfer/consensus/initial_consensus/filtered/${VARIANT}
readonly OLDDIR=/.mounts/labs/simpsonlab/users/jdursi/interim_consensus/results/${VARIANT}
readonly MERGEDIR=./qc/compare-to-interim/${VARIANT}

samples=$( ls vafs | xargs -n1 basename | grep -v \.tbi | cut -f 1 -d . | sort | uniq )

for sample in $samples
do
    oldfile=${OLDDIR}/${sample}.merged.somatic.indel_normed.vcf   #note! not VARIANT
    newfile=${NEWDIR}/${sample}.consensus.${VARIANT}.vcf.gz

    if [ ! -f $newfile ] 
    then
        echo "${sample}: new file not present"
        continue
    fi
    if [ ! -f $oldfile ]
    then
        echo "${sample}: old file not present"
        continue
    fi
    echo -n ${sample}
    newcalls=$( zgrep -cv "^#" $newfile )
    oldcalls=$( grep -cv "^#" $oldfile )
    if [ $newcalls -ne $oldcalls ]
    then
        echo ": mismatch number of calls (new: ${newcalls}, old: ${oldcalls})"
    else
        echo ""
    fi
    if [ ${newcalls} -eq 0 ] || [ ${oldcalls} -eq 0 ]
    then
        continue
    fi

    outfile=${MERGEDIR}/${sample}.comparison.vcf
    mergevcf -l old,new \
        ${oldfile} <( zgrep -v "^##contig" ${newfile} ) \
        --ncallers \
        -o ${outfile}
done
